import { Habit } from "./models/types";

export const INITIAL_HABITS: Habit[] = [
    {
      id: 1,
      title: "Work from highest priority",
      deadline: new Date(2021, 2, 14),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "work",
      streak: 5,
    },
    {
      id: 2,
      title: "Use console.log for debugging",
      deadline: new Date(2021, 4, 1),
      description: "Lorem ipsum dolor sit amet.",
      list: "work",
      streak: 2,
    },
    {
      id: 3,
      title: "Work from highest priority",
      deadline: new Date(2021, 3, 23),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "work",
      streak: 1,
    },
    {
      id: 4,
      title: "Use console.log for debugging",
      deadline: new Date(2021, 5, 8),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "work",
      streak: 3,
    },
    {
      id: 5,
      title: "Sleep at 10:30pm every weekday",
      deadline: new Date(2021, 2, 14),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "rest",
      streak: 5,
    },
    {
      id: 6,
      title: "Wake up at 7am every weekday",
      deadline: new Date(2021, 4, 1),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "rest",
      streak: 2,
    },
    {
      id: 7,
      title: "Sleep before 10:30pm every weekday",
      deadline: new Date(2021, 3, 23),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "rest",
      streak: 1,
    },
    {
      id: 8,
      title: "Wake up at 7am every weekday",
      deadline: new Date(2021, 5, 8),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "rest",
      streak: 3,
    },
    {
      id: 9,
      title: "Workout 5x a week",
      deadline: new Date(2021, 2, 14),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "sport",
      streak: 5,
    },
    {
      id: 10,
      title: "Run 7x a week",
      deadline: new Date(2021, 4, 1),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "sport",
      streak: 2,
    },
    {
      id: 11,
      title: "Workout 5x a week",
      deadline: new Date(2021, 3, 23),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "sport",
      streak: 1,
    },
    {
      id: 12,
      title: "Run 7x a week",
      deadline: new Date(2021, 5, 8),
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      list: "sport",
      streak: 3,
    },
  ];
